#!/usr/bin/env node

var uuid = require('./uuid'),
    input = '',
    stats = {
      docs: 0,
      messages: 0,
      changes: 0
    };

// null is not an object
var isObject = function (obj) {
  return Boolean(obj && typeof obj === 'object');
};

var processData = function(data) {
  var data = JSON.parse(data);
  if (data.docs) {
    data = data.docs;
  } else if (data.rows) {
    data = data.rows;
  } else if (!Array.isArray(data)) {
    data = [data];
  }
  data.forEach(function(doc) {
    // skip null values
    if (!isObject(doc)) {
      return;
    }
    stats.docs++;
    doc.scheduled_tasks.forEach(function(task) {
      task.messages.forEach(function(msg) {
        stats.messages++;
        if (!msg.uuid) {
          msg.uuid = uuid.v4();
          stats.changes++;
        }
      });
    });
  });
  return data;
};

process.stdin.setEncoding('utf8');

process.stdin.on('data', function (chunk) {
  input += chunk;
});

process.stdin.on('end', function () {
  process.stdout.write(JSON.stringify({
    docs: processData(input)
  }));
  console.error(stats);
});
