language: node_js
sudo: false
node_js:
  - "6.3"
  - "5.6"

env:
  - COUCH_URL=http://admin:pass@localhost:5984/medic

before_script:
  - curl -X PUT http://localhost:5984/_config/admins/admin -d '"pass"'
  - npm install grunt-cli -g
  - npm install -g mocha
  - curl -X PUT localhost:5984/medic
  - git clone https://github.com/medic/medic-webapp.git
  - npm install kanso -g
  - cd medic-webapp
  - npm install
  - grunt default
  - kanso push $COUCH_URL
  - cd -

script: 
  - grunt test

services:
  - couchdb

notifications:
  webhooks: 
    urls:
      - https://medic.slack.com/services/hooks/travis?token=xcYT8yusfEdSwLskhBxK4Vwj
    on_success: change
    on_failure: always
  email:
    recipients:
      - dev@medicmobile.org

