language: node_js
sudo: false
node_js: 
  - "node"
  - "6.5"

before_script:
  - npm install grunt-cli -g

script: 
  - grunt ci

notifications:
  webhooks: 
    urls:
      - https://medic.slack.com/services/hooks/travis?token=xcYT8yusfEdSwLskhBxK4Vwj
    on_success: change
    on_failure: always
  email:
    recipients:
      - dev@medicmobile.org
