language: node_js
sudo: false
node_js:
  - "6.3"
  - "5.6"
  - "0.12"

before_script:
  - npm install grunt-cli -g

script: 
  - grunt test

notifications:
  webhooks: 
    urls:
      - https://medic.slack.com/services/hooks/travis?token=xcYT8yusfEdSwLskhBxK4Vwj
    on_success: change
    on_failure: always
  email:
    recipients:
      - dev@medicmobile.org

