#!/bin/bash -eu

# we assume that the admin user already exists

echo "[$0] creating the PARENT_PLACE..."
curl -X PUT \
	--data '{ "_id":"PARENT_PLACE", "type":"district_hospital", "name":"Big Parent Hospital" }' \
	"$COUCH_URL/PARENT_PLACE"

echo "[$0] creating user: bob..."
curl -X POST \
	-H 'Content-Type: application/json' \
	--data '{
	  "username":"bob",
	  "password":"secret",
	  "place":{
	     "_id":"fixture:bobville",
	     "type":"health_center",
	     "name":"Bobville",
	     "parent":"PARENT_PLACE"
	  },
	  "contact":{
	    "name":"Bob"
	  },
	  "roles":["district-manager", "kujua_user", "data_entry", "district_admin"]
	}' \
	"$API_URL/api/v1/users"

echo "[$0] Finished."
